ticket-monster/lab3-sources/src/main/java/org/jboss/jdf/examples/view/ShowBean.java
package org.jboss.jdf.examples.view;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;
import javax.ejb.SessionContext;
import javax.ejb.Stateful;
import javax.enterprise.context.Conversation;
import javax.enterprise.context.ConversationScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceContextType;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;

import org.jboss.jdf.example.ticketmonster.model.Show;
import org.jboss.jdf.example.ticketmonster.model.Event;
import org.jboss.jdf.example.ticketmonster.model.Venue;

/**
 * Backing bean for Show entities.
 * <p>
 * This class provides CRUD functionality for all Show entities. It focuses
 * purely on Java EE 6 standards (e.g. <tt>&#64;ConversationScoped</tt> for
 * state management, <tt>PersistenceContext</tt> for persistence,
 * <tt>CriteriaBuilder</tt> for searches) rather than introducing a CRUD framework or
 * custom base class.
 */

@Named
@Stateful
@ConversationScoped
public class ShowBean implements Serializable
{

   private static final long serialVersionUID = 1L;

   /*
    * Support creating and retrieving Show entities
    */

   private Long id;

   public Long getId()
   {
      return this.id;
   }

   public void setId(Long id)
   {
      this.id = id;
   }

   private Show show;

   public Show getShow()
   {
      return this.show;
   }

   @Inject
   private Conversation conversation;

   @PersistenceContext(type = PersistenceContextType.EXTENDED)
   private EntityManager entityManager;

   public String create()
   {

      this.conversation.begin();
      return "create?faces-redirect=true";
   }

   public void retrieve()
   {

      if (FacesContext.getCurrentInstance().isPostback())
      {
         return;
      }

      if (this.conversation.isTransient())
      {
         this.conversation.begin();
      }

      if (this.id == null)
      {
         this.show = this.example;
      }
      else
      {
         this.show = findById(getId());
      }
   }

   public Show findById(Long id)
   {

      return this.entityManager.find(Show.class, id);
   }

   /*
    * Support updating and deleting Show entities
    */

   public String update()
   {
      this.conversation.end();

      try
      {
         if (this.id == null)
         {
            this.entityManager.persist(this.show);
            return "search?faces-redirect=true";
         }
         else
         {
            this.entityManager.merge(this.show);
            return "view?faces-redirect=true&id=" + this.show.getId();
         }
      }
      catch (Exception e)
      {
         FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(e.getMessage()));
         return null;
      }
   }

   public String delete()
   {
      this.conversation.end();

      try
      {
         this.entityManager.remove(findById(getId()));
         this.entityManager.flush();
         return "search?faces-redirect=true";
      }
      catch (Exception e)
      {
         FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(e.getMessage()));
         return null;
      }
   }

   /*
    * Support searching Show entities with pagination
    */

   private int page;
   private long count;
   private List<Show> pageItems;

   private Show example = new Show();

   public int getPage()
   {
      return this.page;
   }

   public void setPage(int page)
   {
      this.page = page;
   }

   public int getPageSize()
   {
      return 10;
   }

   public Show getExample()
   {
      return this.example;
   }

   public void setExample(Show example)
   {
      this.example = example;
   }

   public void search()
   {
      this.page = 0;
   }

   public void paginate()
   {

      CriteriaBuilder builder = this.entityManager.getCriteriaBuilder();

      // Populate this.count

      CriteriaQuery<Long> countCriteria = builder.createQuery(Long.class);
      Root<Show> root = countCriteria.from(Show.class);
      countCriteria = countCriteria.select(builder.count(root)).where(getSearchPredicates(root));
      this.count = this.entityManager.createQuery(countCriteria).getSingleResult();

      // Populate this.pageItems

      CriteriaQuery<Show> criteria = builder.createQuery(Show.class);
      root = criteria.from(Show.class);
      TypedQuery<Show> query = this.entityManager.createQuery(criteria.select(root).where(getSearchPredicates(root)));
      query.setFirstResult(this.page * getPageSize()).setMaxResults(getPageSize());
      this.pageItems = query.getResultList();
   }

   private Predicate[] getSearchPredicates(Root<Show> root)
   {

      CriteriaBuilder builder = this.entityManager.getCriteriaBuilder();
      List<Predicate> predicatesList = new ArrayList<Predicate>();

      Event event = this.example.getEvent();
      if (event != null)
      {
         predicatesList.add(builder.equal(root.get("event"), event));
      }
      Venue venue = this.example.getVenue();
      if (venue != null)
      {
         predicatesList.add(builder.equal(root.get("venue"), venue));
      }

      return predicatesList.toArray(new Predicate[predicatesList.size()]);
   }

   public List<Show> getPageItems()
   {
      return this.pageItems;
   }

   public long getCount()
   {
      return this.count;
   }

   /*
    * Support listing and POSTing back Show entities (e.g. from inside an
    * HtmlSelectOneMenu)
    */

   public List<Show> getAll()
   {

      CriteriaQuery<Show> criteria = this.entityManager.getCriteriaBuilder().createQuery(Show.class);
      return this.entityManager.createQuery(criteria.select(criteria.from(Show.class))).getResultList();
   }

   @Resource
   private SessionContext sessionContext;

   public Converter getConverter()
   {

      final ShowBean ejbProxy = this.sessionContext.getBusinessObject(ShowBean.class);

      return new Converter()
      {

         @Override
         public Object getAsObject(FacesContext context, UIComponent component, String value)
         {

            return ejbProxy.findById(Long.valueOf(value));
         }

         @Override
         public String getAsString(FacesContext context, UIComponent component, Object value)
         {

            if (value == null)
            {
               return "";
            }

            return String.valueOf(((Show) value).getId());
         }
      };
   }

   /*
    * Support adding children to bidirectional, one-to-many tables
    */

   private Show add = new Show();

   public Show getAdd()
   {
      return this.add;
   }

   public Show getAdded()
   {
      Show added = this.add;
      this.add = new Show();
      return added;
   }
}

ticket-monster/lab3-sources/src/main/webapp/resources/scaffold/pageTemplate.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<h:head>
	<title>#{empty pageTitle ? '{#pageTitle}' : pageTitle}</title>
	<link rel="icon" href="#{resource['favicon.ico']}" />
	<h:outputStylesheet name="bootstrap.css" />
	<h:outputStylesheet name="forge-style.css" />
</h:head>

<h:body>
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<h:link id="brandLink" outcome="/admin/index.xhtml" styleClass="brand">Demo</h:link>
				<div class="nav-collapse collapse">
					<ul class="nav">
						<li><a href="http://forge.jboss.org/docs/important_plugins/ui-scaffolding.html">How to Customize</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>

	<div class="container forgecontainer">
		<div id="navigation">
			<h:link id="homeLink" outcome="/admin/index.xhtml">
				<img src="#{resource['forge-logo.png']}" alt="Forge... get hammered" border="0" />
			</h:link>
			<ul>
				<li>
					<h:link outcome="/admin/booking/search" value="Booking"/>
				</li>
				<li>
					<h:link outcome="/admin/event/search" value="Event"/>
				</li>
				<li>
					<h:link outcome="/admin/eventCategory/search" value="Event Category"/>
				</li>
				<li>
					<h:link outcome="/admin/mediaItem/search" value="Media Item"/>
				</li>
				<li>
					<h:link outcome="/admin/performance/search" value="Performance"/>
				</li>
				<li>
					<h:link outcome="/admin/section/search" value="Section"/>
				</li>
				<li>
					<h:link outcome="/admin/sectionAllocation/search" value="Section Allocation"/>
				</li>
				<li>
					<h:link outcome="/admin/show/search" value="Show"/>
				</li>
				<li>
					<h:link outcome="/admin/ticket/search" value="Ticket"/>
				</li>
				<li>
					<h:link outcome="/admin/ticketCategory/search" value="Ticket Category"/>
				</li>
				<li>
					<h:link outcome="/admin/ticketPrice/search" value="Ticket Price"/>
				</li>
				<li>
					<h:link outcome="/admin/venue/search" value="Venue"/>
				</li>
			</ul>
		</div>

		<div id="content">
			<h1>
				<ui:insert name="header" />
			</h1>
			<h2>
				<ui:insert name="subheader" />
			</h2>

			<ui:insert name="main" />
		</div>
	</div>

	<footer>
		<div id="footer-wrapper">
	    	<p>Powered by <a href="http://jboss.org/forge">Forge</a></p>
	    </div>
	</footer>

</h:body>
</html>

ticket-monster/lab3-sources/src/main/webapp/resources/scaffold/paginator.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions"
	xmlns:ui="http://java.sun.com/jsf/facelets">
	
	<h:panelGroup styleClass="paginator" rendered="#{paginatorBean.count gt paginatorBean.pageSize}">
		<!-- Use commandLink, not outputLink, so that search criteria is not lost -->
		<h:commandLink styleClass="btn btn-primary" rendered="#{paginatorBean.page gt 0}">
			<f:param name="page" value="#{paginatorBean.page - 1}"/>
			&lt; Previous 
		</h:commandLink>
		<h:outputText styleClass="paginator-content" value="#{paginatorBean.page * paginatorBean.pageSize + 1} to #{paginatorBean.page * paginatorBean.pageSize + fn:length(paginatorBean.pageItems)} (of #{paginatorBean.count})"/>
		<h:commandLink styleClass="btn btn-primary" rendered="#{(paginatorBean.page + 1) * paginatorBean.pageSize lt paginatorBean.count}">
			<f:param name="page" value="#{paginatorBean.page + 1}"/>
			Next &gt;
		</h:commandLink>
	</h:panelGroup>

</ui:composition>